image: node:alpine

stages:
  - build
  - test

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - npm build

test:
  stage: test
  cache:
    paths:
      - node_modules/
    policy: pull
  script: npm test
