image: node:alpine

stages:
  - build
  - test

dependencies:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm ci

test:
  stage: test
  cache:
    paths:
      - node_modules/
    policy: pull
  script: npm test
