image: node:alpine

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

dependencies:
  stage: build
  script:
    - npm ci --prefer-offline --no-audit

test:
  stage: test
  script: npm test
