image: node:alpine
stages:
  - build-and-test
build-and-test:
  stage: build-and-test
  cache:
    key: node-modules-cache-v2-${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline --no-audit --loglevel error
    - npm run build
    - npm test
