image: node:alpine

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

dependencies:
  stage: build
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script: npm test
