image: node:alpine
stages:
  - build-and-test
build-and-test:
  stage: build-and-test
  cache:
    paths:
      - .npm/
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - npm test
