version: 2.1
jobs:
  'Build & Test':
    docker:
      image: 'circleci/node:14'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run build
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - 'Build & Test'
