version: 2.1
jobs:
  build:
    docker:
      image: node:alpine
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
  test:
    docker:
      image: node:alpine
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build
        - test