version: 2.1
jobs:
  'Build and Test':
    docker:
      - image: 'node:alpine'
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-v3-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci --cache .npm --prefer-offline --no-audit --loglevel error
      - save_cache:
          key: node-modules-cache-v3-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - .npm/
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - 'Build and Test'
