version: 2.1
jobs:
  'Build and Test':
    docker:
      - image: 'node:alpine'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm run build
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - 'Build and Test'
