version: 2.1
jobs:
  'Build and Test':
    docker:
      - image: 'node:alpine'
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: node-modules-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run: npm run build
      - run: npm test
workflows:
    build-and-test:
      jobs:
        - 'Build and Test'
